--- 
PALMERA:
  bmp: "*.ini, *.bat"
MMS: 
  bmp: "*.ini, *.dbf, *.tsk"
  bpl: "borlndmm.dll, cc3260mt.dll"
TID: 
  bmp: "*.bmp, *.ini"
  bpl: "bdertl60.bpl, dbrtl60.bpl, rtl60.bpl, vcl60.bpl, vcldb60.bpl"
MMW:
  mm: "cyassl-3.2.0, myizip_z, microx_t"
  mmm: "microp, ucs_ms, ucs_dt, ucs_mm, ucs_mu"
MMM:
  mm: "cyassl-3.2.0, myizip_z, microx_t"
  mmm: "microp, ucs_ms, ucs_dt, ucs_mm"

#mail_recipients_dev: 'gerasimov.vyacheslav@ucscards.ru, titaev.leonid@ucscards.ru, shitikov.sergei@ucscards.ru, petelin.konstantin@ucscards.ru, konovalov.sergei@ucscards.ru, a.kustov@ucscards.ru'
mail_recipients_dev: a.kustov@ucscards.ru
# upload url
nexus_url:   "http://10.255.250.50:8081/repository/orpo"
nexus_url_1: "http://10.255.252.161:8081/repository/orpo"
nexus_url_test: "http://10.255.252.161:8081/repository/test"
# dnld url
svn_url: svn/scm/svn/dev
       
