--- 
#for borland.groovy
MMS: 
  app_list: "mmseod.exe,*.ini,*.dbf,*.tsk"
  lib: "borlndmm.dll,cc3260mt.dll"
PALMERA:
  app_list: "palmerauloade.exe,*.ini,*.bat"
PASSKEY:
  app_list: "passkey.exe,*.dll"
TID: 
  printCfg: "*.bmp,*.ini"
  app_list: "cardpro.exe,cardpro.ini"
  lib: "bdertl60.bpl, dbrtl60.bpl, rtl60.bpl, vcl60.bpl, vcldb60.bpl"
#for mm_win.groovy
MMW:
  mm: "cyassl-3.2.0,myizip_z,myizip_u,microx_t"
  mmm: "microp,ucs_ms,ucs_dt,ucs_mu,ucs_mm,setup_p"
  arch: "Win32,x64"
#for mm_nix.groovy
MMX:
  mm: "cyassl-3.2.0,myizip_z,microx_t"
  mmm: "microp,ucs_ms,ucs_dt,ucs_mm"
  arch:
#for chk_sql.groovy
SQL:
  list: "spaceToUnderscore.sh,pthUpload.sh,pthChecker.sh,xdbChecker.sh" 
#
#mail_recipients_dev: 'gerasimov.vyacheslav@ucscards.ru, titaev.leonid@ucscards.ru, shitikov.sergei@ucscards.ru, petelin.konstantin@ucscards.ru, konovalov.sergei@ucscards.ru, a.kustov@ucscards.ru'
mail_recipients_dev: a.kustov@ucscards.ru
# upload url
nexus_url:   "http://10.255.250.50:8081/repository/orpo"
nexus_url_1: "http://10.255.252.161:8081/repository/orpo"
nexus_url_test: "http://10.255.252.161:8081/repository/test"
#nexus_maven: "http://10.255.252.161:8081/repository/ucs_repo"
# dnld url
svn_url: '172.16.10.230/scm/svn/dev'
       
